# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\mac\code\2021\PyQt5-template\ui\文件校验工具_stack.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(600, 400)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(Form)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.label_3 = QtWidgets.QLabel(self.page)
        self.label_3.setGeometry(QtCore.QRect(150, 60, 221, 41))
        self.label_3.setStyleSheet("color: rgb(243,253,253);\n"
"font: 20pt \"黑体\";")
        self.label_3.setObjectName("label_3")
        self.button_file3 = QtWidgets.QPushButton(self.page)
        self.button_file3.setGeometry(QtCore.QRect(320, 180, 100, 100))
        self.button_file3.setStyleSheet("\n"
"#button_file3{\n"
"    image:url(:/file_list/open.png);\n"
"}")
        self.button_file3.setText("")
        self.button_file3.setFlat(True)
        self.button_file3.setObjectName("button_file3")
        self.line = QtWidgets.QFrame(self.page)
        self.line.setGeometry(QtCore.QRect(0, 370, 591, 16))
        self.line.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")
        self.button_file4 = QtWidgets.QPushButton(self.page)
        self.button_file4.setGeometry(QtCore.QRect(450, 180, 100, 100))
        self.button_file4.setStyleSheet("\n"
"#button_file4{\n"
"    image:url(:/file_list/open.png);\n"
"}")
        self.button_file4.setText("")
        self.button_file4.setFlat(True)
        self.button_file4.setObjectName("button_file4")
        self.label_5 = QtWidgets.QLabel(self.page)
        self.label_5.setGeometry(QtCore.QRect(200, 280, 81, 21))
        self.label_5.setStyleSheet("font: 10pt \"黑体\";\n"
"color: rgb(164,164,164);")
        self.label_5.setObjectName("label_5")
        self.button_file1 = QtWidgets.QPushButton(self.page)
        self.button_file1.setGeometry(QtCore.QRect(60, 180, 100, 100))
        self.button_file1.setStyleSheet("\n"
"#button_file1{\n"
"    image:url(:/file_list/open.png);\n"
"}")
        self.button_file1.setText("")
        self.button_file1.setFlat(True)
        self.button_file1.setObjectName("button_file1")
        self.label_6 = QtWidgets.QLabel(self.page)
        self.label_6.setGeometry(QtCore.QRect(330, 280, 81, 21))
        self.label_6.setStyleSheet("font: 10pt \"黑体\";\n"
"color: rgb(164,164,164);")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.page)
        self.label_7.setGeometry(QtCore.QRect(460, 280, 81, 21))
        self.label_7.setStyleSheet("font: 10pt \"黑体\";\n"
"color: rgb(164,164,164);")
        self.label_7.setObjectName("label_7")
        self.button_mini = QtWidgets.QPushButton(self.page)
        self.button_mini.setGeometry(QtCore.QRect(530, 10, 20, 20))
        self.button_mini.setStyleSheet("\n"
"#button_mini{\n"
"    image:url(:/mini/icon_mini.png);\n"
"}\n"
"")
        self.button_mini.setText("")
        self.button_mini.setFlat(True)
        self.button_mini.setObjectName("button_mini")
        self.button_close = QtWidgets.QPushButton(self.page)
        self.button_close.setGeometry(QtCore.QRect(560, 10, 20, 20))
        self.button_close.setStyleSheet("\n"
"#button_close{\n"
"    image:url(:/close/icon_close_normal.png);\n"
"}\n"
"#button_close:hover{\n"
"    image:url(:/close/icon_close_hover.png);\n"
"}\n"
"#button_close:pressed{\n"
"    image:url(:/close/icon_close_click.png);\n"
"}")
        self.button_close.setText("")
        self.button_close.setFlat(True)
        self.button_close.setObjectName("button_close")
        self.button_file2 = QtWidgets.QPushButton(self.page)
        self.button_file2.setGeometry(QtCore.QRect(190, 180, 100, 100))
        self.button_file2.setStyleSheet("\n"
"#button_file2{\n"
"    image:url(:/file_list/open.png);\n"
"}")
        self.button_file2.setText("")
        self.button_file2.setFlat(True)
        self.button_file2.setObjectName("button_file2")
        self.label_4 = QtWidgets.QLabel(self.page)
        self.label_4.setGeometry(QtCore.QRect(70, 280, 81, 21))
        self.label_4.setStyleSheet("font: 10pt \"黑体\";\n"
"color: rgb(164,164,164);")
        self.label_4.setObjectName("label_4")
        self.label_gou = QtWidgets.QLabel(self.page)
        self.label_gou.setGeometry(QtCore.QRect(40, 50, 81, 91))
        self.label_gou.setStyleSheet("#label_gou{\n"
"    image:url(:/other/gou.png);\n"
"}\n"
"")
        self.label_gou.setText("")
        self.label_gou.setObjectName("label_gou")
        self.background_buttom = QtWidgets.QLabel(self.page)
        self.background_buttom.setGeometry(QtCore.QRect(0, 120, 611, 289))
        self.background_buttom.setStyleSheet("background-color: rgb(233,240,246);")
        self.background_buttom.setText("")
        self.background_buttom.setObjectName("background_buttom")
        self.background_top = QtWidgets.QLabel(self.page)
        self.background_top.setGeometry(QtCore.QRect(0, 0, 611, 120))
        self.background_top.setMaximumSize(QtCore.QSize(16777215, 120))
        self.background_top.setStyleSheet("background-color: rgb(19, 179, 253);")
        self.background_top.setText("")
        self.background_top.setObjectName("background_top")
        self.background_buttom.raise_()
        self.background_top.raise_()
        self.label_3.raise_()
        self.button_file3.raise_()
        self.line.raise_()
        self.button_file4.raise_()
        self.label_5.raise_()
        self.button_file1.raise_()
        self.label_6.raise_()
        self.label_7.raise_()
        self.button_mini.raise_()
        self.button_close.raise_()
        self.button_file2.raise_()
        self.label_4.raise_()
        self.label_gou.raise_()
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setStyleSheet("*{\n"
"    \n"
"    font: 10pt \"黑体\";\n"
"}\n"
"#page_2{\n"
"    background-color: rgb(247,248,248);\n"
"}\n"
"\n"
"QPushButton{\n"
"    color: rgb(220,237,252);\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(35,163,244, 255), stop:1 rgba(23,148,236, 255));\n"
"\n"
"    border: 1px solid rgb(4, 130, 253);\n"
"    border-radius: 5px;\n"
"}\n"
"QPushButton:hover{\n"
"    border-radius: 5px;\n"
"    background-color: rgb(19,179,253);\n"
"    color: rgb(220,237,252);\n"
"}\n"
"QPushButton:pressed{\n"
"    color: rgb(220,237,252);\n"
"    border-radius: 5px;\n"
"    background-color: rgb(23,148,236);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.page_2.setObjectName("page_2")
        self.textBrowser = QtWidgets.QTextBrowser(self.page_2)
        self.textBrowser.setGeometry(QtCore.QRect(60, 100, 211, 251))
        self.textBrowser.setObjectName("textBrowser")
        self.label_10 = QtWidgets.QLabel(self.page_2)
        self.label_10.setGeometry(QtCore.QRect(30, 20, 221, 41))
        self.label_10.setStyleSheet("color: rgb(243,253,253);\n"
"font: 20pt \"黑体\";")
        self.label_10.setObjectName("label_10")
        self.background_top_2 = QtWidgets.QLabel(self.page_2)
        self.background_top_2.setGeometry(QtCore.QRect(0, 0, 611, 71))
        self.background_top_2.setMaximumSize(QtCore.QSize(16777215, 120))
        self.background_top_2.setStyleSheet("background-color: rgb(19, 179, 253);")
        self.background_top_2.setText("")
        self.background_top_2.setObjectName("background_top_2")
        self.widget = QtWidgets.QWidget(self.page_2)
        self.widget.setGeometry(QtCore.QRect(290, 100, 291, 251))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.button_addfile_1 = QtWidgets.QPushButton(self.widget)
        self.button_addfile_1.setMinimumSize(QtCore.QSize(0, 40))
        self.button_addfile_1.setStyleSheet("")
        self.button_addfile_1.setObjectName("button_addfile_1")
        self.gridLayout.addWidget(self.button_addfile_1, 1, 0, 1, 1)
        self.button_export_1 = QtWidgets.QPushButton(self.widget)
        self.button_export_1.setMinimumSize(QtCore.QSize(0, 40))
        self.button_export_1.setStyleSheet("")
        self.button_export_1.setObjectName("button_export_1")
        self.gridLayout.addWidget(self.button_export_1, 1, 1, 1, 1)
        self.button_back1 = QtWidgets.QPushButton(self.widget)
        self.button_back1.setMinimumSize(QtCore.QSize(0, 40))
        self.button_back1.setStyleSheet("")
        self.button_back1.setObjectName("button_back1")
        self.gridLayout.addWidget(self.button_back1, 2, 1, 1, 1)
        self.button_process_1 = QtWidgets.QPushButton(self.widget)
        self.button_process_1.setMinimumSize(QtCore.QSize(0, 40))
        self.button_process_1.setStyleSheet("")
        self.button_process_1.setObjectName("button_process_1")
        self.gridLayout.addWidget(self.button_process_1, 2, 0, 1, 1)
        self.background_top_2.raise_()
        self.textBrowser.raise_()
        self.label_10.raise_()
        self.widget.raise_()
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setStyleSheet("*{\n"
"    \n"
"    font: 10pt \"黑体\";\n"
"}\n"
"#page_3{\n"
"    background-color: rgb(247,248,248);\n"
"}\n"
"\n"
"QPushButton{\n"
"    color: rgb(220,237,252);\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(35,163,244, 255), stop:1 rgba(23,148,236, 255));\n"
"\n"
"    border: 1px solid rgb(4, 130, 253);\n"
"    border-radius: 5px;\n"
"}\n"
"QPushButton:hover{\n"
"    border-radius: 5px;\n"
"    background-color: rgb(19,179,253);\n"
"    color: rgb(220,237,252);\n"
"}\n"
"QPushButton:pressed{\n"
"    color: rgb(220,237,252);\n"
"    border-radius: 5px;\n"
"    background-color: rgb(23,148,236);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.page_3.setObjectName("page_3")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.page_3)
        self.textBrowser_2.setGeometry(QtCore.QRect(60, 100, 211, 251))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.background_top_3 = QtWidgets.QLabel(self.page_3)
        self.background_top_3.setGeometry(QtCore.QRect(0, 0, 611, 71))
        self.background_top_3.setMaximumSize(QtCore.QSize(16777215, 120))
        self.background_top_3.setStyleSheet("background-color: rgb(19, 179, 253);")
        self.background_top_3.setText("")
        self.background_top_3.setObjectName("background_top_3")
        self.widget_2 = QtWidgets.QWidget(self.page_3)
        self.widget_2.setGeometry(QtCore.QRect(290, 100, 291, 251))
        self.widget_2.setObjectName("widget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.button_process_2 = QtWidgets.QPushButton(self.widget_2)
        self.button_process_2.setMinimumSize(QtCore.QSize(0, 40))
        self.button_process_2.setStyleSheet("")
        self.button_process_2.setObjectName("button_process_2")
        self.gridLayout_2.addWidget(self.button_process_2, 0, 0, 1, 1)
        self.button_export_2 = QtWidgets.QPushButton(self.widget_2)
        self.button_export_2.setMinimumSize(QtCore.QSize(0, 40))
        self.button_export_2.setStyleSheet("")
        self.button_export_2.setObjectName("button_export_2")
        self.gridLayout_2.addWidget(self.button_export_2, 0, 1, 1, 1)
        self.button_addfile_2 = QtWidgets.QPushButton(self.widget_2)
        self.button_addfile_2.setMinimumSize(QtCore.QSize(0, 40))
        self.button_addfile_2.setStyleSheet("")
        self.button_addfile_2.setObjectName("button_addfile_2")
        self.gridLayout_2.addWidget(self.button_addfile_2, 1, 0, 1, 1)
        self.button_back2 = QtWidgets.QPushButton(self.widget_2)
        self.button_back2.setMinimumSize(QtCore.QSize(0, 40))
        self.button_back2.setStyleSheet("")
        self.button_back2.setObjectName("button_back2")
        self.gridLayout_2.addWidget(self.button_back2, 1, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.page_3)
        self.label_12.setGeometry(QtCore.QRect(30, 20, 221, 41))
        self.label_12.setStyleSheet("color: rgb(243,253,253);\n"
"font: 20pt \"黑体\";")
        self.label_12.setObjectName("label_12")
        self.textBrowser_2.raise_()
        self.widget_2.raise_()
        self.background_top_3.raise_()
        self.label_12.raise_()
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setStyleSheet("*{\n"
"    \n"
"    font: 10pt \"黑体\";\n"
"}\n"
"#page_4{\n"
"    background-color: rgb(247,248,248);\n"
"}\n"
"\n"
"QPushButton{\n"
"    color: rgb(220,237,252);\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(35,163,244, 255), stop:1 rgba(23,148,236, 255));\n"
"\n"
"    border: 1px solid rgb(4, 130, 253);\n"
"    border-radius: 5px;\n"
"}\n"
"QPushButton:hover{\n"
"    border-radius: 5px;\n"
"    background-color: rgb(19,179,253);\n"
"    color: rgb(220,237,252);\n"
"}\n"
"QPushButton:pressed{\n"
"    color: rgb(220,237,252);\n"
"    border-radius: 5px;\n"
"    background-color: rgb(23,148,236);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.page_4.setObjectName("page_4")
        self.widget_3 = QtWidgets.QWidget(self.page_4)
        self.widget_3.setGeometry(QtCore.QRect(290, 100, 291, 251))
        self.widget_3.setObjectName("widget_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget_3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.button_addfile_3 = QtWidgets.QPushButton(self.widget_3)
        self.button_addfile_3.setMinimumSize(QtCore.QSize(0, 40))
        self.button_addfile_3.setStyleSheet("")
        self.button_addfile_3.setObjectName("button_addfile_3")
        self.gridLayout_3.addWidget(self.button_addfile_3, 1, 0, 1, 1)
        self.button_export_3 = QtWidgets.QPushButton(self.widget_3)
        self.button_export_3.setMinimumSize(QtCore.QSize(0, 40))
        self.button_export_3.setStyleSheet("")
        self.button_export_3.setObjectName("button_export_3")
        self.gridLayout_3.addWidget(self.button_export_3, 1, 1, 1, 1)
        self.button_back3 = QtWidgets.QPushButton(self.widget_3)
        self.button_back3.setMinimumSize(QtCore.QSize(0, 40))
        self.button_back3.setStyleSheet("")
        self.button_back3.setObjectName("button_back3")
        self.gridLayout_3.addWidget(self.button_back3, 2, 1, 1, 1)
        self.button_process_3 = QtWidgets.QPushButton(self.widget_3)
        self.button_process_3.setMinimumSize(QtCore.QSize(0, 40))
        self.button_process_3.setStyleSheet("")
        self.button_process_3.setObjectName("button_process_3")
        self.gridLayout_3.addWidget(self.button_process_3, 2, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.page_4)
        self.label_11.setGeometry(QtCore.QRect(30, 20, 221, 41))
        self.label_11.setStyleSheet("color: rgb(243,253,253);\n"
"font: 20pt \"黑体\";")
        self.label_11.setObjectName("label_11")
        self.background_top_4 = QtWidgets.QLabel(self.page_4)
        self.background_top_4.setGeometry(QtCore.QRect(0, 0, 611, 71))
        self.background_top_4.setMaximumSize(QtCore.QSize(16777215, 120))
        self.background_top_4.setStyleSheet("background-color: rgb(19, 179, 253);")
        self.background_top_4.setText("")
        self.background_top_4.setObjectName("background_top_4")
        self.textBrowser_3 = QtWidgets.QTextBrowser(self.page_4)
        self.textBrowser_3.setGeometry(QtCore.QRect(60, 100, 211, 251))
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.background_top_4.raise_()
        self.widget_3.raise_()
        self.label_11.raise_()
        self.textBrowser_3.raise_()
        self.stackedWidget.addWidget(self.page_4)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setStyleSheet("*{\n"
"    \n"
"    font: 10pt \"黑体\";\n"
"}\n"
"#page_5{\n"
"    background-color: rgb(247,248,248);\n"
"}\n"
"\n"
"QPushButton{\n"
"    color: rgb(220,237,252);\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(35,163,244, 255), stop:1 rgba(23,148,236, 255));\n"
"\n"
"    border: 1px solid rgb(4, 130, 253);\n"
"    border-radius: 5px;\n"
"}\n"
"QPushButton:hover{\n"
"    border-radius: 5px;\n"
"    background-color: rgb(19,179,253);\n"
"    color: rgb(220,237,252);\n"
"}\n"
"QPushButton:pressed{\n"
"    color: rgb(220,237,252);\n"
"    border-radius: 5px;\n"
"    background-color: rgb(23,148,236);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.page_5.setObjectName("page_5")
        self.background_top_5 = QtWidgets.QLabel(self.page_5)
        self.background_top_5.setGeometry(QtCore.QRect(0, 0, 611, 71))
        self.background_top_5.setMaximumSize(QtCore.QSize(16777215, 120))
        self.background_top_5.setStyleSheet("background-color: rgb(19, 179, 253);")
        self.background_top_5.setText("")
        self.background_top_5.setObjectName("background_top_5")
        self.widget_4 = QtWidgets.QWidget(self.page_5)
        self.widget_4.setGeometry(QtCore.QRect(290, 100, 291, 251))
        self.widget_4.setObjectName("widget_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.widget_4)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.button_addfile_4 = QtWidgets.QPushButton(self.widget_4)
        self.button_addfile_4.setMinimumSize(QtCore.QSize(0, 40))
        self.button_addfile_4.setStyleSheet("")
        self.button_addfile_4.setObjectName("button_addfile_4")
        self.gridLayout_4.addWidget(self.button_addfile_4, 1, 0, 1, 1)
        self.button_export_4 = QtWidgets.QPushButton(self.widget_4)
        self.button_export_4.setMinimumSize(QtCore.QSize(0, 40))
        self.button_export_4.setStyleSheet("")
        self.button_export_4.setObjectName("button_export_4")
        self.gridLayout_4.addWidget(self.button_export_4, 1, 1, 1, 1)
        self.button_back4 = QtWidgets.QPushButton(self.widget_4)
        self.button_back4.setMinimumSize(QtCore.QSize(0, 40))
        self.button_back4.setStyleSheet("")
        self.button_back4.setObjectName("button_back4")
        self.gridLayout_4.addWidget(self.button_back4, 2, 1, 1, 1)
        self.button_process_4 = QtWidgets.QPushButton(self.widget_4)
        self.button_process_4.setMinimumSize(QtCore.QSize(0, 40))
        self.button_process_4.setStyleSheet("")
        self.button_process_4.setObjectName("button_process_4")
        self.gridLayout_4.addWidget(self.button_process_4, 2, 0, 1, 1)
        self.textBrowser_4 = QtWidgets.QTextBrowser(self.page_5)
        self.textBrowser_4.setGeometry(QtCore.QRect(60, 100, 211, 251))
        self.textBrowser_4.setObjectName("textBrowser_4")
        self.label_13 = QtWidgets.QLabel(self.page_5)
        self.label_13.setGeometry(QtCore.QRect(30, 20, 221, 41))
        self.label_13.setStyleSheet("color: rgb(243,253,253);\n"
"font: 20pt \"黑体\";")
        self.label_13.setObjectName("label_13")
        self.stackedWidget.addWidget(self.page_5)
        self.verticalLayout.addWidget(self.stackedWidget)

        self.retranslateUi(Form)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_3.setText(_translate("Form", "文件校验工具"))
        self.label_5.setText(_translate("Form", "详设文件校验"))
        self.label_6.setText(_translate("Form", "前评报告校验"))
        self.label_7.setText(_translate("Form", "后评报告校验"))
        self.label_4.setText(_translate("Form", "需求文件校验"))
        self.label_10.setText(_translate("Form", "需求文件校验"))
        self.button_addfile_1.setText(_translate("Form", "开始处理"))
        self.button_export_1.setText(_translate("Form", "导出结果"))
        self.button_back1.setText(_translate("Form", "返回主页"))
        self.button_process_1.setText(_translate("Form", "添加文件"))
        self.button_process_2.setText(_translate("Form", "开始处理"))
        self.button_export_2.setText(_translate("Form", "导出结果"))
        self.button_addfile_2.setText(_translate("Form", "添加文件"))
        self.button_back2.setText(_translate("Form", "返回主页"))
        self.label_12.setText(_translate("Form", "设计文件校验"))
        self.button_addfile_3.setText(_translate("Form", "开始处理"))
        self.button_export_3.setText(_translate("Form", "导出结果"))
        self.button_back3.setText(_translate("Form", "返回主页"))
        self.button_process_3.setText(_translate("Form", "添加文件"))
        self.label_11.setText(_translate("Form", "前评报告校验"))
        self.button_addfile_4.setText(_translate("Form", "开始处理"))
        self.button_export_4.setText(_translate("Form", "导出结果"))
        self.button_back4.setText(_translate("Form", "返回主页"))
        self.button_process_4.setText(_translate("Form", "添加文件"))
        self.label_13.setText(_translate("Form", "后评报告校验"))
import worktable_img_rc
